version: '3.8'

services:
  speakver-app:
    build: .
    container_name: speakver_container
    ports:
      - "7860:7860" # Порт для доступа к Gradio (Хост:Контейнер)
    volumes:
      # Тяжелые папки и результаты работы монтируются локально
      - ./datasets:/app/datasets
      - ./reports:/app/reports
      - ./experiments:/app/experiments
      - ./debug_audio:/app/debug_audio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Предоставляет контейнеру доступ ко всем GPU хоста
              capabilities: [gpu]
    restart: unless-stopped
