services:
  speakver-app:
    build: .

    container_name: speakver_container

    env_file:
      - ./config/envs/docker.env

    ports:
      - "127.0.0.1:7860:7860"

    volumes:
      - ./datasets:/app/datasets
      - ./runs:/app/runs
      - ./reports:/app/reports
      - ./debug_audio:/app/debug_audio

    gpus: all

    restart: unless-stopped