[project]
name = "SpeakVer"
version = "0.2.1"
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "black",
    "commitizen",
    "pytest",
    "ruff",
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.1"
version_provider = "pep621"
tag_format = "v$version"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "pyproject.toml:version",
]
changelog_file = "CHANGELOG.md"